# Generated by Django 5.2 on 2025-05-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
